Kevin
semphoenix/Gamified-Kanban pull request #35
Opened 2023-05-07 19:42 UTC by thekevinliao

need someone to double check prize rendering in profile page.

2023-05-07 20:10 UTC, semphoenix approved these changes

2023-05-07 20:23 UTC, ajitk123 approved these changes

2023-05-07 21:00 UTC, ajitk123 requested changes
the kanban page looks good but I can't see the link to signup in the login page

2023-05-08 03:10 UTC, ajitk123 approved these changes

2023-05-08 03:12 UTC, merged